### ISSUE TITLE
[BUG]: Error at login

### ISSUE THREAD

**Issue by git-avc** [kid1194/frappe_alerts#2]
**Describe the bug**
Can't login after app install. Receive 
File "apps/alerts/alerts/utils/alert.py", line 98, in cache_alerts
    Criterion.all(
TypeError: Criterion.all() takes from 0 to 1 positional arguments but 2 were given

**To Reproduce**
Install APP
Try to login
See console

**Expected behavior**
Should get login

**Comment by kid1194** [comment]
@git-avc Thanks a lot bro for your fix..

**Comment by lan9635** [comment]
so how to fix it. I get the same error.

**Comment by kid1194** [comment]
@lan9635 Sorry for that, I forgot to push the fix 😅

Thank you for reminding me bro..

Please update and everything will be fine..

Best regards..

**Comment by lan9635** [comment]
After the update, I still fixed two places:
1 access.py add: from frappe import _
2 boot.py add: import frappe
Then, there were no errors。
But, the For Roles and/or the For Users do not get the alerts

**Comment by lan9635** [comment]
![图片](https://github.com/kid1194/frappe_alerts/assets/84449561/66a286bb-649f-45a1-98e1-9cca4a4611cc)

**Comment by kid1194** [comment]
@lan9635 Hey bro..

I'm sorry for the troubles you went through..

And thank you so much for reporting these bugs..

I have remodel the app code a bit, fixed these missing imports and improved the overall performance a bit..

So if you can, please update, test it and report back any problem you face..

I can't thank you enough for doing this..

Best regards..
