### ISSUE TITLE
[BUG]: '(' was never closed (alert.py, line 121)

### ISSUE THREAD

**Issue by satishkakani** [kid1194/frappe_alerts#3]
**Describe the bug**
Installing the app to the site is failing with the below error line

An error occurred while installing alerts: '(' was never closed (alert.py, line 121)

Installed Version is 15

Below is the complete error code

Installing alerts...
An error occurred while installing alerts: '(' was never closed (alert.py, line 121)
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 462, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['xxxxxxx.in'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('alerts',)
      force = False
      _install_app = <function install_app at 0x7f2ac5f92440>
      filelock = <function filelock at 0x7f2ac5f920e0>
      exit_code = 0
      site = ''
      app = 'alerts'
      err = SyntaxError("'(' was never closed", ('apps/alerts/alerts/utils/alert.py', 121, 11, '    qry = (\n', 121, 0))
  File "apps/frappe/frappe/installer.py", line 311, in install_app
    frappe.get_attr(after_install)()
      name = 'alerts'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7f2ac46bfa30>
      sync_for = <function sync_for at 0x7f2ac46cc550>
      sync_customizations = <function sync_customizations at 0x7f2ac60d8dc0>
      sync_fixtures = <function sync_fixtures at 0x7f2ac46cc790>
      app_hooks = {'after_install': ['alerts.setup.install.after_install'], 'app_color': ['blue'], 'app_description': ['Frappe app that displays custom alerts to specific recipients.'], 'app_email': ['kid1194@gmail.com'], 'app_icon': ['octicon octicon-bell'], 'app_include_js': ['alerts.bundle.js'], 'app_license': ['MIT'], 'app_name': ['alerts'], 'app_publisher': ['Ameen Ahmed (Level Up)'], 'app_title': ['Alerts'], 'extend_bootinfo': ['alerts.utils.boot.extend'], 'on_login': ['alerts.utils.access.on_login'], 'scheduler_events': {'daily': ['alerts.utils.alert.update_alerts']}}
      after_install = 'alerts.setup.install.after_install'
  File "apps/frappe/frappe/__init__.py", line 1672, in get_attr
    return getattr(get_module(modulename), methodname)
      method_string = 'alerts.setup.install.after_install'
      app_name = 'alerts'
      modulename = 'alerts.setup.install'
      methodname = 'after_install'
  File "apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
      modulename = 'alerts.setup.install'
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
      name = 'alerts.setup.install'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      name = 'alerts.setup.install'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      name = 'alerts.setup.install'
      import_ = <function _gcd_import at 0x7f2ac7d7b400>
      module = <exception while printing> Traceback (most recent call last):
          File "env/lib/python3.10/site-packages/traceback_with_variables/core.py", line 222, in _to_cropped_str
            raw = print_(obj)
          File "apps/frappe/frappe/utils/__init__.py", line 329, in dict_printer
            if key in v:
        TypeError: argument of type 'object' is not iterable

  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      name = 'alerts.setup.install'
      import_ = <function _gcd_import at 0x7f2ac7d7b400>
      path = ['apps/alerts/alerts/setup']
      parent = 'alerts.setup'
      parent_module = <module 'alerts.setup' from 'apps/alerts/alerts/setup/__init__.py'>
      spec = ModuleSpec(name='alerts.setup.install', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>, origin='apps/alerts/alerts/setup/install.py')
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      spec = ModuleSpec(name='alerts.setup.install', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>, origin='apps/alerts/alerts/setup/install.py')
      module = <module 'alerts.setup.install' from 'apps/alerts/alerts/setup/install.py'>
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      self = <_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>
      module = <module 'alerts.setup.install' from 'apps/alerts/alerts/setup/install.py'>
      code = <code object <module> at 0x7f2ac2afaad0, file "apps/alerts/alerts/setup/install.py", line 1>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      f = <built-in function exec>
      args = (<code object <module> at 0x7f2ac2afaad0, file "apps/alerts/alerts/setup/install.py", line 1>, {'__name__': 'alerts.setup.install', '__doc__': None, '__package__': 'alerts.setup', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>, '__spec__': ModuleSpec(name='alerts.setup.install', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>, origin='apps/alerts/alerts/setup/install.py'), '__file__': 'apps/alerts/alerts/setup/install.py', '__cached__': 'apps/alerts/alerts/setup/__pycache__/install.cpython-310.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_froze...
      kwds = {}
  File "apps/alerts/alerts/setup/install.py", line 7, in <module>
    from alerts.utils.type import add_type
      __name__ = 'alerts.setup.install'
      __doc__ = None
      __package__ = 'alerts.setup'
      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>
      __spec__ = ModuleSpec(name='alerts.setup.install', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2adb850>, origin='apps/alerts/alerts/setup/install.py')
      __file__ = 'apps/alerts/alerts/setup/install.py'
      __cached__ = 'apps/alerts/alerts/setup/__pycache__/install.cpython-310.pyc'
      __builtins__ = {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, ...
  File "apps/alerts/alerts/utils/__init__.py", line 7, in <module>
    from .alert import *
      __name__ = 'alerts.utils'
      __doc__ = None
      __package__ = 'alerts.utils'
      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2b073d0>
      __spec__ = ModuleSpec(name='alerts.utils', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7f2ac2b073d0>, origin='apps/alerts/alerts/utils/__init__.py', submodule_search_locations=['apps/alerts/alerts/utils'])
      __path__ = ['apps/alerts/alerts/utils']
      __file__ = 'apps/alerts/alerts/utils/__init__.py'
      __cached__ = 'apps/alerts/alerts/utils/__pycache__/__init__.cpython-310.pyc'
      __builtins__ = {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, ...
builtins.SyntaxError: '(' was never closed (alert.py, line 121)

**Comment by kid1194** [comment]
@satishkakani Hey bro..

Thank you so much for reporting this. I can't tell you how much grateful I am..

I hope you like my token of appreciation in the Readme file..

I have fixed the bug and made so many changes and improvements, so kindly please give it another try and let me know if there are any problems.. 

Best regards..

**Comment by kid1194** [comment]
@satishkakani Thanks for your help and support bro..

I have managed to fix all the bugs and I hope that you and everyone else find this module useful..

But if you face any problem the please let me know..

Best regards..
