### ISSUE TITLE
[BUG]: Installation Issue

### ISSUE THREAD

**Issue by davygarg** [kid1194/frappe_alerts#4]
Getting Error while installing alerts to a site

alerts.utils.alert.update_alerts is not a valid method: invalid syntax (alert.py, line 205)
alerts.utils.update.auto_check_for_update is not a valid method: invalid syntax (alert.py, line 205)
Updating Dashboard for alerts
An error occurred while installing alerts: invalid syntax (alert.py, line 205)
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 446, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['erp.mt.support'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('alerts',)
      force = False
      _install_app = <function install_app at 0x7fcc27791ea0>
      filelock = <function filelock at 0x7fcc27791b40>
      exit_code = 0
      site = 'erp.mt.support'
      app = 'alerts'
      err = SyntaxError('invalid syntax', ('apps/alerts/alerts/utils/alert.py', 205, 14, '    names [v for v in names if v and isinstance(v, str)]\n', 205, 17))
  File "apps/frappe/frappe/installer.py", line 320, in install_app
    frappe.get_attr(after_sync)()  #
      name = 'alerts'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7fcc25ec39a0>
      sync_for = <function sync_for at 0x7fcc25ed44c0>
      sync_customizations = <function sync_customizations at 0x7fcc278d08b0>
      sync_fixtures = <function sync_fixtures at 0x7fcc25ed4700>
      app_hooks = {'after_migrate': ['alerts.setup.migrate.after_migrate'], 'after_sync': ['alerts.setup.install.after_sync'], 'app_color': ['blue'], 'app_description': ['Frappe app that displays custom alerts to specific recipients.'], 'app_email': ['kid1194@gmail.com'], 'app_icon': ['octicon octicon-bell'], 'app_include_js': ['alerts.bundle.js'], 'app_license': ['MIT'], 'app_name': ['alerts'], 'app_publisher': ['Ameen Ahmed (Level Up)'], 'app_title': ['Alerts'], 'extend_bootinfo': ['alerts.utils.boot.extend'], 'on_login': ['alerts.utils.access.on_login'], 'scheduler_events': {'daily': ['alerts.utils.alert.update_alerts', 'alerts.utils.update.auto_check_for_update']}}
      installed_apps = ['frappe', 'erpnext', 'payments', 'india_compliance', 'business_theme_v14', 'print_designer', 'frappe_system_monitor', 'webshop', 'builder']
      fn = 'india_compliance.install.after_app_install'
      after_sync = 'alerts.setup.install.after_sync'
  File "apps/alerts/alerts/setup/install.py", line 15, in after_sync
    from alerts.utils.settings import settings
  File "apps/alerts/alerts/utils/__init__.py", line 7, in <module>
    from .alert import (
      __name__ = 'alerts.utils'
      __doc__ = None
      __package__ = 'alerts.utils'
      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x7fcc246e2770>
      __spec__ = ModuleSpec(name='alerts.utils', loader=<_frozen_importlib_external.SourceFileLoader object at 0x7fcc246e2770>, origin='apps/alerts/alerts/utils/__init__.py', submodule_search_locations=['apps/alerts/alerts/utils'])
      __path__ = ['apps/alerts/alerts/utils']
      __file__ = 'apps/alerts/alerts/utils/__init__.py'
      __cached__ = 'apps/alerts/alerts/utils/__pycache__/__init__.cpython-310.pyc'
      __builtins__ = {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, ...
builtins.SyntaxError: invalid syntax (alert.py, line 205)

**Comment by kid1194** [comment]
@davygarg Thanks a lot bro for reporting this..

I really appreciate your effort..

I have fixed the bug, so please give it another try and let me know if you face any problem..

Best regards..

**Comment by kid1194** [comment]
@davygarg Thanks for your help and support bro..

I have managed to fix all the bugs and I hope that you and everyone else find this module useful..

But if you face any problem the please let me know..

Best regards..
