### ISSUE TITLE
doctype opens in a unusable[BUG]: 

### ISSUE THREAD

**Issue by neomrx** [kid1194/frappe_alerts#7]
I am currently facing an issue with the “Alerts” tool and require your assistance. Here are the details:
After a clean installation, the doctype opens in a malformed and unusable state. However, when I open it in doctype type edit, I can see the other fields correctly.
Screenshot  in Attach if it helps illustrate the issue.
<img width="744" alt="Capture" src="https://github.com/kid1194/frappe_alerts/assets/32833895/b417863d-a188-412c-98a8-a6c3fad365fa">

**Comment by kid1194** [comment]
@neomrx Hey bro..

Thank you for reporting this bug..
This is happening due to a bug in the doctype's form js..

I will try to fix it and it will help a lot if you post a screenshot of the browser console..

Best regards..

**Comment by neomrx** [comment]
Thank you for your answer .
please find bellow the console log, hope that help investigating the problem.
 
Best regards.

Log :

jquery.js:3773  jQuery.Deferred exception: $isFn is not defined ReferenceError: $isFn is not defined
    at HTMLDocument.<anonymous> (http://jh-digital.local:8000/assets/alerts/dist/js/alerts.bundle.B6QGEWCD.js:1559:183)
    at mightThrow (http://jh-digital.local:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:1922:42)
    at process (http://jh-digital.local:8000/assets/frappe/dist/js/libs.bundle.LLRFRX7M.js:1957:25) undefined
jQuery2.Deferred.exceptionHook @ jquery.js:3773
process @ jquery.js:3551
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 10 plus de cadres
Afficher moins
jquery.js:3783  Uncaught ReferenceError: $isFn is not defined
    at HTMLDocument.<anonymous> (alerts.bundle.js:1253:24)
    at mightThrow (jquery.js:3479:29)
    at process (jquery.js:3547:12)
(anonymes) @ alerts.bundle.js:1253
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
jQuery2.readyException @ jquery.js:3782
(anonymes) @ jquery.js:3802
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
process @ jquery.js:3567
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 21 plus de cadres
Afficher moins
script_manager.js:32  ƒ (frm) {
        frappe.alerts.on('ready change', function() { this.setup_form(frm); });
    }
_handler @ script_manager.js:32
runner @ script_manager.js:109
(anonymes) @ script_manager.js:125
trigger @ script_manager.js:122
setup @ script_manager.js:238
setup @ form.js:115
refresh @ form.js:428
render @ formview.js:107
show_doc @ formview.js:73
make @ formview.js:18
show @ factory.js:25
render_page @ router.js:323
render @ router.js:302
route @ router.js:157
await in route (asynchrone)
push_state @ router.js:485
Promise.finally.frappe.route_flags @ router.js:376
set_route @ router.js:365
frappe.set_route @ router.js:561
render_new_doc @ formview.js:101
(anonymes) @ formview.js:85
callback @ model.js:317
callback @ request.js:85
200 @ request.js:133
(anonymes) @ request.js:305
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9617
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
(anonymes) @ model.js:309
with_doc @ model.js:299
fetch_and_render @ formview.js:80
show_doc @ formview.js:75
make_and_show @ formview.js:32
(anonymes) @ formview.js:15
with_doctype @ model.js:232
make @ formview.js:12
show @ factory.js:25
render_page @ router.js:323
render @ router.js:302
route @ router.js:157
await in route (asynchrone)
set_route @ desk.js:161
startup @ desk.js:92
Application @ desk.js:30
frappe.start_app @ desk.js:12
(anonymes) @ desk.js:25
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 16 plus de cadres
Afficher moins
alert_type__js:17  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on')
    at setup (alert_type__js:17:23)
    at _handler (script_manager.js:30:12)
    at runner (script_manager.js:109:16)
    at script_manager.js:125:5
    at Array.forEach (<anonymous>)
    at ScriptManager.trigger (script_manager.js:122:22)
    at ScriptManager.setup (script_manager.js:238:8)
    at FrappeForm.setup (form.js:115:23)
    at FrappeForm.refresh (form.js:428:10)
    at FormFactory.render (formview.js:107:45)
setup @ alert_type__js:17
_handler @ script_manager.js:30
runner @ script_manager.js:109
(anonymes) @ script_manager.js:125
trigger @ script_manager.js:122
setup @ script_manager.js:238
setup @ form.js:115
refresh @ form.js:428
render @ formview.js:107
show_doc @ formview.js:73
make @ formview.js:18
show @ factory.js:25
render_page @ router.js:323
render @ router.js:302
route @ router.js:157
await in route (asynchrone)
push_state @ router.js:485
Promise.finally.frappe.route_flags @ router.js:376
set_route @ router.js:365
frappe.set_route @ router.js:561
render_new_doc @ formview.js:101
(anonymes) @ formview.js:85
callback @ model.js:317
callback @ request.js:85
200 @ request.js:133
(anonymes) @ request.js:305
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9617
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
(anonymes) @ model.js:309
with_doc @ model.js:299
fetch_and_render @ formview.js:80
show_doc @ formview.js:75
make_and_show @ formview.js:32
(anonymes) @ formview.js:15
with_doctype @ model.js:232
make @ formview.js:12
show @ factory.js:25
render_page @ router.js:323
render @ router.js:302
route @ router.js:157
await in route (asynchrone)
set_route @ desk.js:161
startup @ desk.js:92
Application @ desk.js:30
frappe.start_app @ desk.js:12
(anonymes) @ desk.js:25
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 16 plus de cadres
Afficher moins

**Comment by kid1194** [comment]
@neomrx Thank you bro for your help..

I hope that the last commit fixes this problem..
Please give it another try and let me know if you face any problem..

Best regards..

**Comment by neomrx** [comment]
Thank you for your support,
at this step, i can save new Alert, i  can preview but i can't submit.
please find bellow the console log,

Best regards.


Log :
       
        POST http://jh-digital.local:8000/api/method/frappe.desk.form.save.savedocs 500 (INTERNAL SERVER ERROR)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymes) @ form.js:820
Promise.then (asynchrone)
(anonymes) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymes) @ form.js:750
save @ form.js:747
(anonymes) @ form.js:842
Promise.then (asynchrone)
(anonymes) @ form.js:837
primary_action @ messages.js:34
(anonymes) @ dialog.js:192
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Afficher 4 plus de cadres
Afficher moins
request.js:473  Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1046, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1029, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 388, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1129, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 960, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1320, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1302, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 957, in fn
    return method_object(*args, **kwargs)
  File "apps/alerts/alerts/alerts/doctype/alert/alert.py", line 57, in on_submit
    self._send_alert()
  File "apps/alerts/alerts/alerts/doctype/alert/alert.py", line 122, in _send_alert
    send_alert(data)
  File "apps/alerts/alerts/utils/alert.py", line 104, in send_alert
    add_type_data(data.alert_type, data)
AttributeError: 'dict' object has no attribute 'alert_type'

(anonymes) @ request.js:473
frappe.request.cleanup @ request.js:471
(anonymes) @ request.js:325
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
_call @ save.js:246
save @ save.js:23
frappe.ui.form.save @ save.js:273
(anonymes) @ form.js:820
Promise.then (asynchrone)
(anonymes) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:811
(anonymes) @ form.js:750
save @ form.js:747
(anonymes) @ form.js:842
Promise.then (asynchrone)
(anonymes) @ form.js:837
primary_action @ messages.js:34
(anonymes) @ dialog.js:192
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
Afficher 8 plus de cadres
Afficher moins

**Comment by kid1194** [comment]
@neomrx Thank you so much bro for your patience, I have been a bit busy..

I have fixed the problem based on the error log you posted..
I hope everything works this time..

Best regards..

**Comment by neomrx** [comment]
Thank you for your time.
an other step, an other error.
submiting ok.

Best regards.
![image](https://github.com/kid1194/frappe_alerts/assets/32833895/580e65d7-5170-42df-9b56-6e9b7ebdc158)

Log :

assets.js:70 localStorage cleared
assets.js:27 Cleared App Cache.
assets.js:70 localStorage cleared
request.js:279 
        
        
        POST http://jh-digital.local:8000/api/method/alerts.utils.user_alerts 500 (INTERNAL SERVER ERROR)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
_get_alerts @ alerts.bundle.js:826
setTimeout (asynchrone)
$timeout @ alerts.bundle.js:110
_setup @ alerts.bundle.js:820
(anonymes) @ alerts.bundle.js:241
callback @ request.js:85
200 @ request.js:133
(anonymes) @ request.js:305
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9617
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
Alerts @ alerts.bundle.js:759
(anonymes) @ alerts.bundle.js:1267
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 18 plus de cadres
Afficher moins
request.js:473  Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/alerts/alerts/utils/alert.py", line 88, in user_alerts
    data["alerts"] = get_user_alerts(frappe.session.user)
  File "apps/alerts/alerts/utils/alert.py", line 169, in get_user_alerts
    qry = type_join_query(qry, doc.alert_type)
  File "apps/alerts/alerts/utils/type.py", line 75, in type_join_query
    doc.display_priority._as("priority"),
AttributeError: 'Field' object has no attribute '_as'

(anonymes) @ request.js:473
frappe.request.cleanup @ request.js:471
(anonymes) @ request.js:325
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
_get_alerts @ alerts.bundle.js:826
setTimeout (asynchrone)
$timeout @ alerts.bundle.js:110
_setup @ alerts.bundle.js:820
(anonymes) @ alerts.bundle.js:241
callback @ request.js:85
200 @ request.js:133
(anonymes) @ request.js:305
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9617
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
Alerts @ alerts.bundle.js:759
(anonymes) @ alerts.bundle.js:1267
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 22 plus de cadres
Afficher moins
alerts.bundle.js:205  [ALERTS] Getting user alerts failed. The request sent raised an error.
$console @ alerts.bundle.js:205
_error @ alerts.bundle.js:212
(anonymes) @ alerts.bundle.js:846
(anonymes) @ alerts.bundle.js:250
500 @ request.js:221
(anonymes) @ request.js:356
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
_get_alerts @ alerts.bundle.js:826
setTimeout (asynchrone)
$timeout @ alerts.bundle.js:110
_setup @ alerts.bundle.js:820
(anonymes) @ alerts.bundle.js:241
callback @ request.js:85
200 @ request.js:133
(anonymes) @ request.js:305
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9617
(anonymes) @ jquery.js:9878
load (asynchrone)
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:279
frappe.call @ request.js:109
request @ alerts.bundle.js:256
Alerts @ alerts.bundle.js:759
(anonymes) @ alerts.bundle.js:1267
mightThrow @ jquery.js:3479
process @ jquery.js:3547
setTimeout (asynchrone)
(anonymes) @ jquery.js:3592
fire @ jquery.js:3213
fireWith @ jquery.js:3343
fire @ jquery.js:3351
fire @ jquery.js:3213
fireWith @ jquery.js:3343
ready @ jquery.js:3834
completed @ jquery.js:3844
Afficher 22 plus de cadres
Afficher moins

**Comment by kid1194** [comment]
@neomrx Thank you buddy for reporting this and my apologies for any trouble I have caused..

I have fixed my silly mistake so please give it another try and let me know if you face any problem..

Best regards..

**Comment by neomrx** [comment]
@kid1194 , the solution works wonderfully, and I am very pleased with the results, I am convinced that it can be leveraged on multiple levels.
my gratitude for your diligence and patience throughout the process.
Thank you once again, and I look forward to further collaboration.
Best regards,

**Comment by kid1194** [comment]
@neomrx Thank you bro for everything..

I'm glad that it finally worked as expected..

If you find any problem please let me know..

Best regards..
